name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            source ~/.bashrc
            cd /home/on/project/fashion-brand-lumie
            git pull origin main
            npm install
            npm run build
            pm2 restart fashion-brand-lumie